// The render vocabulary, re-exported so a consumer can import it from here.
export {
	approxEngine,
	createParagraphEngine,
	encodePng,
	exportPixelSize,
	getFontMetrics,
	MAX_EXPORT_DIMENSION,
	MAX_SUPERSAMPLE,
	type MeasureText,
	readFontMetrics,
	registerFontMetrics,
	resolveExportScale,
	resolveSupersample,
	type SpanFont,
	type TextEngine,
} from "@freshcoat-js/engine";
export {
	ASSET_URI_PREFIX,
	type AssetHashMismatch,
	type AssetSrcRewriter,
	assetDataUri,
	assetUri,
	attachAssets,
	base64ToBytes,
	bytesToBase64,
	collectAssetRefs,
	detachAssets,
	inlineAssetUrls,
	mapAssetSrcs,
	type PendingAsset,
	parseAssetUri,
	readAssets,
	rehashAssets,
	resolveAssetSrcs,
	type Sha256,
	subtleSha256,
	verifyAssets,
} from "./assets";
export {
	type BarcodeEncodeResult,
	type BarcodeEncoder,
	type BarcodeEncoding,
	defaultQuietZone,
	errorCorrectionRange,
	getBarcodeEncoder,
	isLinearSymbology,
	isSquareSymbology,
	SYMBOLOGIES,
	setBarcodeEncoder,
	symbologyLabel,
} from "./barcode-encoder";
export { compile } from "./compile";
export {
	constrainBox,
	fitDesignSize,
	resizeElements,
	resizeTemplate,
} from "./constraints";
export {
	collectFontBytes,
	collectFontRequests,
	defaultFontFamily,
} from "./fonts";
export {
	FORMAT_MAJOR,
	FORMAT_MINOR,
	FORMAT_VERSION,
	type FormatVersionStatus,
	formatVersionStatus,
} from "./format";
export { linearGradientAngle, linearGradientPoints } from "./gradient";
export { substitute } from "./mustache";
export { healElementIds, uniquifyElementIds } from "./normalize";
export { generateMatrix } from "./qr";
export { childElements } from "./tree";
export type {
	Background,
	BakedTextLayout,
	BarcodeElement,
	BarcodeProperties,
	BitmapRole,
	BlendMode,
	CanvasGradientLike,
	CanvasHost,
	CanvasLike,
	CanvasPatternLike,
	CanvasRenderingContext2DLike,
	Command,
	CompiledFrame,
	CompiledTemplate,
	CompileOptions,
	Constraint,
	Constraints,
	DrawBitmapCommand,
	DrawCommand,
	DrawGroupCommand,
	DrawImageCommand,
	DrawPathCommand,
	DrawQrCommand,
	DrawRectCommand,
	DrawTextCommand,
	Element,
	ElementShell,
	ElementType,
	EncodedPaintResult,
	EncodePngOptions,
	ExportConstraint,
	ExportSetting,
	FieldDefinition,
	FieldFormat,
	FieldsSchema,
	Fill,
	FontDescriptor,
	FontFile,
	FontRequest,
	FontResolution,
	FontVMetrics,
	FrameAssets,
	FrameElement,
	FrameProperties,
	GradientStop,
	ImageElement,
	ImageLike,
	ImageProperties,
	InlineAsset,
	KeptPaintResult,
	Layout,
	LayoutChild,
	LeafElement,
	MaskElement,
	MaskProperties,
	PaintOutput,
	PaintResult,
	PaintRuntime,
	PaintWarning,
	QrCodeElement,
	QrCodeProperties,
	RectElement,
	RectProperties,
	ResolvedFill,
	ResolvedFont,
	SetupCommand,
	Shadow,
	ShapeMask,
	Size,
	Stroke,
	Symbology,
	Template,
	TemplateFrame,
	TemplateSource,
	TemplateWarning,
	TextElement,
	TextLine,
	TextLineSpan,
	TextProperties,
	ValidationError,
	ValidationResult,
	Variant,
	Vec2,
	VectorElement,
	VectorProperties,
	VisibilityCondition,
} from "./types";
export { validate, validateValues } from "./validate";
export {
	type ApplyVariantOptions,
	applyVariant,
	checkVariants,
	type VariantElementDelta,
	type VariantIssue,
} from "./variants";
export {
	fieldIsSet,
	isElementVisible,
	pruneHiddenElements,
} from "./visibility";
