// The render vocabulary, re-exported so a consumer can import it from here.
export {
	approxEngine,
	createPaintCache,
	encodePng,
	exportPixelSize,
	getFontMetrics,
	MAX_EXPORT_DIMENSION,
	MAX_SUPERSAMPLE,
	type MeasureText,
	type PaintCache,
	type PaintCacheOptions,
	type PaintCacheStats,
	readFontMetrics,
	type Renderer,
	registerFontMetrics,
	resolveExportScale,
	resolveSupersample,
	type SpanFont,
	type TextEngine,
} from "@freshcoat-js/engine";
export {
	ASSET_URI_PREFIX,
	type AssetHashMismatch,
	type AssetSrcRewriter,
	assetDataUri,
	assetUri,
	attachAssets,
	base64ToBytes,
	bytesToBase64,
	collectAssetRefs,
	detachAssets,
	inlineAssetUrls,
	mapAssetSrcs,
	type PendingAsset,
	parseAssetUri,
	readAssets,
	rehashAssets,
	resolveAssetSrcs,
	type Sha256,
	subtleSha256,
	verifyAssets,
} from "./assets";
export { encodeBarcode } from "./barcode";
export {
	type BarcodeEncodeResult,
	type BarcodeEncoding,
	BEARER_BAR_MODULES,
	bearerBarsOf,
	defaultQuietZone,
	errorCorrectionRange,
	isLinearSymbology,
	isSquareSymbology,
	SYMBOLOGIES,
	symbologyLabel,
} from "./barcode-encoder";
export {
	type BleedMm,
	bleedMm,
	bleedSize,
	type CardSizeMm,
	cardSizeMm,
	extendIntoBleed,
	hasInsets,
	MM_PER_INCH,
	NO_BLEED,
	resolveBleedMm,
	resolveInsets,
	templateBleed,
	templateSafeArea,
} from "./bleed";
export { compile } from "./compile";
export {
	barcodeBox,
	constrainBox,
	fitDesignSize,
	resizeElements,
	resizeTemplate,
	resizeVectorPath,
} from "./constraints";
export {
	collectFontBytes,
	collectFontRequests,
	defaultFontFamily,
	type FontCache,
	type ResolvedTemplateFonts,
	type ResolveTemplateFontsOptions,
	resolveTemplateFonts,
} from "./fonts";
export {
	FORMAT_MAJOR,
	FORMAT_MINOR,
	FORMAT_VERSION,
	type FormatVersionStatus,
	formatVersionStatus,
	minimumFormatVersion,
	raiseFormatVersion,
} from "./format";
export { linearGradientAngle, linearGradientPoints } from "./gradient";
export { ellipsePath, isEllipsePath } from "./ellipse-path";
export { formatImageFocus, parseImageFocus } from "./image-focus";
export {
	parseTrimValue,
	type ResolvedStrokeTrim,
	resolveStrokeTrim,
	type StrokeTrimInput,
} from "./stroke-trim";
export {
	FIELD_ID,
	hasToken,
	type MustacheRef,
	type MustacheSegment,
	type MustacheText,
	parseMustache,
	renameToken,
	substitute,
	tokenIds,
	wholeToken,
} from "./mustache";
export { healElementIds, uniquifyElementIds } from "./normalize";
export { type PrepareOptions, prepareTemplate } from "./prepare";
export { generateMatrix } from "./qr";
export { childElements } from "./tree";
export type {
	Background,
	BakedTextLayout,
	BarcodeElement,
	BarcodeProperties,
	BearerBars,
	BitmapRole,
	BlendMode,
	Command,
	CompiledFrame,
	CompiledTemplate,
	CompileWarning,
	CompileOptions,
	Constraint,
	Constraints,
	DrawBitmapCommand,
	DrawCommand,
	DrawGroupCommand,
	DrawImageCommand,
	DrawPathCommand,
	DrawQrCommand,
	DrawRectCommand,
	DrawTextCommand,
	Element,
	ElementAdjust,
	ElementShell,
	ElementType,
	EncodePngOptions,
	ExportConstraint,
	ExportSetting,
	FieldDefinition,
	FieldFormat,
	FieldsSchema,
	Fill,
	FontDescriptor,
	FontFile,
	FontRequest,
	FontResolution,
	FontVMetrics,
	FrameAssets,
	FrameElement,
	FrameFlexLayout,
	FrameGridLayout,
	FrameProperties,
	FrameWarning,
	Gradient,
	GradientStop,
	GridTrack,
	ImageCrop,
	ImageElement,
	ImageProperties,
	InlineAsset,
	Insets,
	Layout,
	LayoutChild,
	LeafElement,
	MaskElement,
	MaskProperties,
	PaintWarning,
	PrintWarning,
	QrCodeElement,
	QrCodeProperties,
	RectElement,
	RectProperties,
	ResolvedFill,
	ResolvedFont,
	SetupCommand,
	Shadow,
	ShapeMask,
	Sides,
	Size,
	Stroke,
	Symbology,
	Template,
	TemplateFrame,
	TemplateSource,
	TemplateWarning,
	TextElement,
	TextLine,
	TextLineSpan,
	TextProperties,
	ValidationError,
	ValidationResult,
	Variant,
	Vec2,
	VectorElement,
	VectorProperties,
	VisibilityCondition,
} from "./types";
export {
	compiledPattern,
	PATTERN_CACHE_MAX,
	type TextRuleBreak,
	type TextRules,
	textRuleBreaks,
} from "./text-rules";
export { validate, validateValues } from "./validate";
export {
	type ApplyVariantOptions,
	applyVariant,
	checkVariants,
	closestVariant,
	hasShapedVariants,
	isEmptyVariant,
	type VariantElementDelta,
	type VariantIssue,
	variantBase,
	variantSize,
} from "./variants";
export {
	fieldIsSet,
	isElementVisible,
	pruneHiddenElements,
} from "./visibility";
